#!/usr/bin/env bash
#
# Configure a tmux window. Make it so Pulp Smash can test several Pulp systems
# at once.
set -euo pipefail

# create panes
tmux split-window -v
tmux select-layout even-vertical

# configure each pane
tmux send-keys -t 0 'export PULP_SMASH_CONFIG_FILE=fedora-25-pulp-2-14-host-a.json' C-m
tmux send-keys -t 1 'export PULP_SMASH_CONFIG_FILE=fedora-25-pulp-2-14-host-b.json' C-m

# etc
tmux set-window-option synchronize-panes on
tmux send-keys 'source ~/.venvs/pulp-smash/bin/activate' C-m
