- block:

  - name: Install smartmontools
    pacman:
      name: smartmontools

  - name: Install smartd configuration file
    copy:
      src: smartd.conf
      dest: /etc/smartd.conf

  - name: Start and enable smartd
    systemd:
      name: smartd
      state: started
      enabled: yes

  - name: Install scripts for starting SMART scans
    copy:
      src: usr_local_bin/
      dest: /usr/local/bin/
      mode: 0755

  - name: Install units for starting SMART scans
    copy:
      src: etc_systemd_system/
      dest: /etc/systemd/system/

  - name: Start and enable timers for starting SMART scans
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
      daemon_reload: yes
    with_items:
    - smart-test-long.timer
    - smart-test-short.timer

  become: true
