#!/usr/bin/env bash
set -euo pipefail

# Don't send DNS name lookups to dnsmasq.
resolvconf -d br-libvirt.dhcp

# Destroy the dummy network interface and bridge.
ip link set br-libvirt-nic nomaster
ip link set br-libvirt-nic down
ip link delete br-libvirt-nic type dummy
ip link set br-libvirt down
ip link delete br-libvirt type bridge

# vim:set ts=2 sw=2 et:
