set nocompatible        " do not emulate vi's limitations, whatever they are
set nowrap              " learn how to write 80-character wide code, y'all!
set tabstop=4           " tab character treated as four characters wide
set expandtab           " tab inserts spaces instead of tab character...
set shiftwidth=4        " ...specifically, four spaces
set autoindent          " keep current indentation level when starting new line
set incsearch           " incremental search: match as you type
set ignorecase          " ignore case when searching...
set smartcase           " ...except when I use caps in a search term
set scrolloff=2         " start scrolling viewport berore cursor reaches top/bot
set laststatus=2        " always show the status line
set rnu                 " relative line numbers, not absolute numbers
set cursorline          " highlight the current row
set foldmethod=indent   " more convenient than manual, easier than custom
set nofoldenable        " enable folding by default?
let mapleader=","
" TODO: automatically save undo file upon file close
set undofile            " Should the undo tree be saved? Allows persistent undo.
set undodir="~/.vim/undo" " This directory is NOT automatically created.

"nmap n nzz              " center display around cursor when searching for terms
"nmap N Nzz              " .
nmap <F4> :set t_Co=256<CR>:color badwolf<CR>
nmap <F5> :tabprev<CR>
nmap <F6> :tabnew<CR>
nmap <F7> :!ctags -R -o ~/.mytags --exclude='logistix-platform' ~/code<CR>
nmap <F8> :tabnext<CR>
nmap <F9> :NERDTreeToggle<CR>
nmap <F10> :UndotreeToggle<CR>
nmap <F12> :TagbarToggle<CR>
set tags=~/.mytags      " where to find the tags that exuberant ctags generates?

nnoremap <up> <nop>
nnoremap <right> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>

syntax enable           " Well *yes* I want color.
"color jellybeans        " Good for diffing.
color badwolf           " Pink! Red! Lime green!
set background=light    " badwolf's dark variation looks nicer

" Vim doesn't have built-in syntax highlighting for *.pde files, last I checked.
"autocmd! BufNewFile,BufRead *.pde setlocal ft=arduino.vim " Horrid, but better than nothing.
