#
# ~/.bashrc
#

# If not running interactively, don't do anything. Some programs, such as SCP,
# will malfunction if you run the remaining statements in this bashrc.
[[ $- != *i* ]] && return

# Do not display hidden characters \[stuff\]
# Start colorization: \e[XXm
# End colorization: \e[0m
alias grep='grep --color=auto'
alias less='less -Ri'
alias ll='ls -lha --color=auto --group-directories-first'
alias l='ls -lh --color=auto --group-directories-first'
alias ls='ls -h --color=auto --group-directories-first'
alias pacman='pacman-color'
alias rm='rm -I'
alias t='todo.sh'
export EDITOR="vim"
export PS1='[\u@\[\e[0;1m\]\h:\W\[\e[0;0m\]]\$ '
export EMAIL="ichimonji10@gmail.com"
# for vim colorization
if [ "xterm" == "$TERM" ]; then
    export TERM='xterm-256color'
fi

# if raid is plugged in, give status of such when terminal launches
if [ -e /proc/mdstat ]; then
    cat /proc/mdstat
fi
# check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize
# append to the history file, don't overwrite it
shopt -s histappend
