#!/usr/bin/env bash
#
# For each device, start a short SMART self-test.
set -euo pipefail

# Device names taken from smartd(8).
devs=($(ls /dev/hd[a-t] /dev/sd[a-z] /dev/sd[a-c][a-z] /dev/nvme[0-99])) || true
for dev in "${devs[@]}"; do
    smartctl -t short "$dev"
done
