#!/usr/bin/env python3
# coding=utf-8
"""SSH into the currently active Pulp Smash system.

The "currently active" Pulp Smash system is the one named in the Pulp Smash
config file. By default, this file is ``~/.config/pulp_smash/settings.json``.
"""
from subprocess import run

from pulp_smash import config


def main():
    """SSH into the currently active Pulp Smash system."""
    run(['ssh', config.get_config().systems[0].hostname])


if __name__ == '__main__':
    exit(main())
