- block:

  - name: Install nginx
    pacman:
      name: nginx

  - name: Let nginx access transmission's downloads
    user:
      name: http
      groups: transmission
      append: true
      create_home: false

  - name: Install htpasswd file for transmission.ichimonji10.name
    htpasswd:
      name: admin
      password: '{{ transmission_password }}'
      path: /etc/nginx/transmission_ichimonji10_name_downloads.htpasswd
      owner: root
      group: http
      mode: 0640
    when: transmission_password is defined

  - name: Install nginx configuration file
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: Reload nginx

  - name: Create directory for SSL certificates
    file:
      path: /etc/nginx/ssl
      state: directory
      mode: 0700

  - name: Install SSL certificates and certificate keys
    copy:
      src: '{{ item }}'
      dest: /etc/nginx/ssl/
      owner: root
      group: root
      mode: 0600
    loop: '{{ nginx_ssl_files }}'
    when: nginx_ssl_files is defined

  # From ansible-doc: The [copy] module recursively copy facility does not scale
  # to lots (>hundreds) of files. For alternative, see [synchronize] module,
  # which is a wrapper around `rsync'.
  - name: Install files for static websites
    copy:
      src: '{{ item }}'
      dest: /usr/share/nginx/
      owner: root
      group: root
      mode: 0644
      directory_mode: 0755
    loop:
    - www.backtobasicsreading.com
    - www.ichimonji10.name

  - name: Start and enable nginx
    systemd:
      name: nginx.service
      state: started
      enabled: yes
      daemon_reload: yes

  become: true
