#
# ~/.bashrc
#

# If not running interactively, don't do anything
# How does this work???
#[[ $- != *i* ]] && return

# Do not display hidden characters \[stuff\]
# Start colorization: \e[XXm
# End colorization: \e[0m
alias t='todo.sh'
alias grep='grep --color=auto'
alias less='less -i'
alias rm='rm -I'
alias ls='ls -h --color=auto --group-directories-first'
alias l='ls -lh --color=auto --group-directories-first'
alias ll='ls -lha --color=auto --group-directories-first'
export LIBUSBTP=/usr/lib32/libusb.so
export EDITOR="vim"
export PS1='\u@\[\e[33m\]\h\[\e[0m\]:\[\e[36m\]\W\[\e[0m\]\$ '
export EMAIL="ichimonji10@gmail.com"
# for vim colorization
if [ -e /usr/share/terminfo/x/xterm-256color ]; then
    export TERM='xterm-256color'
fi

# if raid is plugged in, give status of such when terminal launches
if [ -e /media/external-raid/ ]; then
    cat /proc/mdstat
fi
# check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize
# append to the history file, don't overwrite it
shopt -s histappend
