# `.bash_profile` is only executed when you initially login to a machine,
# whether by console, ssh, or otherwise. `.bashrc` is executed every time you
# open a new command prompt, even if you're already logged in, and it should
# also be called by `.bash_profile`. `.bash_profile` is great for, say,
# automatically starting X (if your login manager doesn't do that already), or
# for printing out machine stats upon first login. `.bashrc` is great for just
# about everything else.

# If the shell is not running interactively, immediately return. This ensures
# that programs like scp are given a pristine environment.
[[ $- != *i* ]] && return

# This is a kludge.
if [ -n "$TMUX" ]; then
    export TERM=screen-256color
fi

alias d='dirs -v'
alias grep='grep --color=auto'
alias l='ls -1'
alias less='less -R'
alias ll='ls -lha'
alias ls='ls --color=auto --group-directories-first'
alias rm='rm -I'

# See bash(1) or https://wiki.archlinux.org/index.php/Bash/Prompt_customization.
__prompt_command() {
    local exit="$?"

    # local black="\[$(tput setaf 0)\]"
    local red="\[$(tput setaf 1)\]"
    # local green="\[$(tput setaf 2)\]"
    # local yellow="\[$(tput setaf 3)\]"
    # local blue="\[$(tput setaf 4)\]"
    # local purple="\[$(tput setaf 5)\]"
    local turquoise="\[$(tput setaf 6)\]"
    # local white="\[$(tput setaf 7)\]"
    local reset="\[$(tput sgr0)\]"

    # As far as I can tell, there's no reason to export PS1. It's only of use to
    # bash, not sub-processes like vim or git-commit.
    PS1="[${turquoise}\u${reset}@${turquoise}\h${reset}:${turquoise}\W${reset}]"
    if [ "${exit}" == 0 ]; then
        PS1+="[${turquoise}${exit}${reset}]\$ "
    else
        PS1+="[${red}${exit}${reset}]\$ "
    fi
}
PROMPT_COMMAND=__prompt_command

export EDITOR="vim"
export EMAIL="jerebear@protonmail.com"
export PAGER=less
export PATH="$PATH:$HOME/.local/bin"

# Update LINES and COLUMNS after each command if needed.
shopt -s checkwinsize
# Append to the history file instead of overwriting it.
shopt -s histappend
