# `.bash_profile` is only executed when you initially login to a machine,
# whether by console, ssh, or otherwise. `.bashrc` is executed every time you
# open a new command prompt, even if you're already logged in, and it should
# also be called by `.bash_profile`. `.bash_profile` is great for, say,
# automatically starting X (if your login manager doesn't do that already), or
# for printing out machine stats upon first login. `.bashrc` is great for just
# about everything else.

# If the shell is not running interactively, immediately return. This ensures
# that programs like scp are given a pristine environment.
[[ $- != *i* ]] && return

# This is a kludge.
if [ -n "$TMUX" ]; then
    export TERM=screen-256color
fi

alias d='dirs -v'
alias grep='grep --color=auto'
alias l='ls -1'
alias less='less -R'
alias ll='ls -lha'
alias ls='ls --color=auto --group-directories-first'
alias rm='rm -I'

export EDITOR="vim"
export EMAIL="jerebear@protonmail.com"
export PAGER=less
export PATH="$PATH:$HOME/.local/bin"
export PS1="[\[\e[0;36m\]\u\[\e[0;0m\]@\[\e[0;36m\]\h\[\e[0;0m\]:\[\e[0;36m\]\W\[\e[0;0m\]]\$ "

# Update LINES and COLUMNS after each command if needed.
shopt -s checkwinsize
# Append to the history file instead of overwriting it.
shopt -s histappend
