#
# ~/.bashrc
#
# .bashrc vs .bash_profile
# ========================
#
# `.bash_profile` is only executed when you initially login to a machine,
# whether by console, ssh, or otherwise. `.bashrc` is executed every time you
# open a new command prompt, even if you're already logged in, and it should
# also be called by `.bash_profile`. `.bash_profile` is great for, say,
# automatically starting X (if your login manager doesn't do that already), or
# for printing out machine stats _only_ upon first login. `.bashrc` is great
# for just about everything else.
#
# If the shell is not running interactively, immediately return. Some programs,
# such as SCP, will malfunction if you execute statements such as "cat". ($-
# returns a string containing "i" if the shell is interactive)
#
# PS1 hidden characters should be placed inside \[these\]. If not done, the
# cursor position and actual character position will be offset incorrectly.
# Start colorization sequence: \e[XXm
# End colorization sequence: \e[0m
#

[[ $- != *i* ]] && return

alias grep='grep --color=auto'
alias less='less -R'
alias ls='ls      --color=auto --group-directories-first'
alias l='ls       --color=auto --group-directories-first'
alias ll='ls -lha --color=auto --group-directories-first'
alias rm='rm -I'
alias t='todo.sh'

export EDITOR="vim"
export EMAIL="ichimonji10@gmail.com"
export GEM_HOME=~/.gem/ruby/2.0.0
export PS1='[\u@\[\e[1;36m\]\h:\W\[\e[0;0m\]]\$ '
# GEM_HOME: This forces bundler to install gems on a per-user basis, instead of
# system-wide. This matches the default `gem` behaviour on Arch Linux, and it
# also allows gems to be installed without `sudo`.

# Check window size after each command if update LINES and COLUMNS if necessary
shopt -s checkwinsize

# Append to the history file instead of overwriting it.
shopt -s histappend

# rbenv - AUR install
# Adds rbenv shims to `PATH`, enables auto-completion, automatically rehashes
# shims upon shell launch, and makes `rbenv shell` and `rbenv rehash` function
# correctly.
if [[ -a `which rbenv 2>/dev/null` ]]; then
    eval "$(rbenv init -)"
fi

# mdadm
# Show status of mdadm raid array if `/proc/mdstat` is present.
if [[ -e /proc/mdstat ]]; then
    cat /proc/mdstat
fi
