#
# ~/.bashrc
#
# .bashrc vs .bash_profile
# ========================
#
# `.bash_profile` is only executed when you initially login to a machine,
# whether by console, ssh, or otherwise. `.bashrc` is executed every time you
# open a new command prompt, even if you're already logged in, and it should
# also be called by `.bash_profile`. `.bash_profile` is great for, say,
# automatically starting X (if your login manager doesn't do that already), or
# for printing out machine stats upon first login. `.bashrc` is great for just
# about everything else.
#
# interactive user check
# ======================
#
[[ $- != *i* ]] && return
#
# If the shell is not running interactively, immediately return. Some programs,
# such as SCP, will malfunction if you execute statements such as `cat`. `$-`
# returns a string containing "i" if the shell is interactive.

alias grep='grep --color=auto'
alias less='less -R'
alias ls='ls --color=auto --group-directories-first'
alias l='ls -1'
alias ll='ls -lha'
alias rm='rm -I'
alias d='dirs -v'

if [ -n "$TMUX" ]; then
    export TERM=screen-256color
else
    export TERM=xterm-256color
fi

export EDITOR="vim"
export EMAIL="ichimonji10@gmail.com"
export PAGER=less
export PS1="[\[\e[0;36m\]\u\[\e[0;0m\]@\[\e[0;36m\]\h\[\e[0;0m\]:\[\e[0;36m\]\W\[\e[0;0m\]]\$ "

# Check window size after each command if update LINES and COLUMNS if necessary
shopt -s checkwinsize
# Append to the history file instead of overwriting it.
shopt -s histappend
