set nocompatible        " Do not emulate vi's quirks.
set nowrap              " Don't wrap lines.
set textwidth=80        " Any line longer than this is automatically broken at
                        " a whitespace boundary.
set autoindent          " Keep current indentation level when starting new line
set expandtab           " Tab key insert spaces instead of tab character.
set shiftwidth=4        " Number of spaces to insert when indenting.
set tabstop=4           " Tab character appears as four whitespace characters.
set incsearch           " incremental search: match as you type
set ignorecase          " Ignore case when searching...
set smartcase           " ...except when I use caps in a search term.
set cursorline          " Highlight the current row.
set laststatus=2        " Always show the status line.
set rnu                 " Display relative line numbers.
set ruler               " Show cursor's current row and column number.
set showcmd             " Show (partial) command.
set foldmethod=indent   " More convenient than manual, easier than custom.
set nofoldenable        " Don't fold things by default, though.
set backspace=2         " e.g. allows me to backspace in insert mode.
set scrolloff=2         " Buffer between cursor and top+bottom edge of viewport.
"set undofile            " Should the undo tree be saved? Allows persistent undo.
"set undodir="~/.vim/undo" " This directory is NOT automatically created.
                        " TODO: automatically save undo file upon file close
let mapleader=","

nmap <F4> :set t_Co=256<CR>:color badwolf<CR>
nmap <F5> :tabprev<CR>
nmap <F6> :tabnew<CR>
nmap <F7> :!ctags -R -o ~/.mytags ~/code<CR>
nmap <F8> :tabnext<CR>
nmap <F9> :NERDTreeToggle<CR>
nmap <F10> :UndotreeToggle<CR>
nmap <F12> :TagbarToggle<CR>
set tags=~/.mytags      " where to find the tags that exuberant ctags generates?

nnoremap <up> <nop>
nnoremap <right> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>

syntax enable           " Well *yes* I want color.
"color jellybeans        " Good for diffing.
color badwolf           " Pink! Red! Lime green!
set background=light    " badwolf's dark variation looks nicer

" Vim doesn't have built-in syntax highlighting for *.pde files, last I checked.
"autocmd! BufNewFile,BufRead *.pde setlocal ft=arduino.vim " Horrid, but better than nothing.
