#!/usr/bin/env bash
#
# Generate cscope and ctags databases and launch cscope.
#
# This script is customized for searching through the Linux kernel source code.
# The temporary files generated by this script, such as the cscope database, are
# placed in `cscope_dir`.

# Die if any command returns non-zero.
set -e
# Die if an uninitialized var is used.
set -u

linux_dir=~/code/linux-3.6.11
cscope_dir=~/.cscope
cscope_file=cscope.files

echo "Creating \"$cscope_dir\"..."
test -d "$cscope_dir" || mkdir "$cscope_dir"

echo Creating list of files to index...
cd / # Make `find` print absolute path names.
find "$linux_dir" \
    \( \
        -path "$linux_dir/arch/*" ! -path "$linux_dir/arch/x86*" -o \
        -path "$linux_dir/Documentation*" -o \
        -path "$linux_dir/scripts*" -o \
        -path "$linux_dir/tools*" -o \
        -path "$linux_dir/drivers*" \
    \) -prune -o \
    -name "*.[chxsS]" -print > "$cscope_dir/$cscope_file"

cd "$cscope_dir"
echo Creating cscope database...
cscope -b -q -k -i "$cscope_file"
echo Creating ctags database...
ctags -L "$cscope_file"
echo Starting cscope...
cscope -d
